// components/Layout/Footer.tsx
import { FC } from "react";

export const Footer: FC = () => {
    return (
        <footer className="p-4 flex justify-center bg-primary text-on-primary">
            <div className="max-w-xl">
                Designed &amp; Built by 
                <span> <a href="https://github.com/amalahanaja" target="__blank" className="font-bold hover:underline"> Alfian Akmal Hanantio</a> </span>
                using 
                <span> <a href="https://nextjs.org/" target="__blank" className="text-slate-100 font-bold hover:underline">NextJS</a> &amp; </span>
                <span> <a href="https://tailwindcss.com/" target="__blank" className="font-bold text-blue-100 hover:underline">TailwindCSS</a> </span>
            </div>
        </footer>
    )
}

// src/lib/components/Footer.svelte
<script lang="ts">
	const highlight = ['font-semibold', 'transition-all', 'duration-150'];
	const highlightPrimary = [...highlight, 'hover:text-primary'].join(' ');
	const highlightSecondary = [...highlight, 'hover:text-secondary'].join(' ');
</script>

<footer class="bg-surface px-4 py-8 flex justify-center">
	<div class="max-w-md">
		Loosely designed in <span class={highlightPrimary}>Figma</span> and coded in
		<span class={highlightSecondary}>Visual Studio Code</span> by
		<span class={highlightPrimary}>Alfian Akmal Hanantio</span>. Built with
		<span class={highlightSecondary}>Svelte</span> and
		<span class={highlightPrimary}>Tailwind CSS</span>, deployed with
		<span class={highlightSecondary}>Vercel</span>. All text is set in the Outfit typeface.
	</div>
</footer>
